{% set version = "4-17" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rjags
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rjags_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rjags/rjags_{{ version }}.tar.gz
  sha256: e911e7ca7e1acd8b25b8b02f59aa4bf4a1b406569907b0295a3082fadaff4334

build:
  number: 0
  skip: true  # [win]
  rpaths:
    - lib/R/lib/
    - lib/
    - lib/JAGS/modules-4/

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-coda                       # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib('c') }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib('m2w64_c') }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-coda >=0.13
    - jags 4.*
  run:
    - r-base
    - r-coda >=0.13
    - jags 4.*

test:
  commands:
    - $R -e "library('rjags')"           # [not win]
    - "\"%R%\" -e \"library('rjags')\""  # [win]

about:
  home: http://mcmc-jags.sourceforge.net
  license: GPL-2.0-only
  summary: Interface to the JAGS MCMC library.
  license_family: GPL2
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - micknudsen
